name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag caddyflare:$(date +%s)
